spawn: save,-85,9,243,30,-30
#\nでマイクラ内チャット欄での改行になります
#カラーコードも使用可能
Onsen:
  Text: "&a[温泉機能についてのお知らせ]\n&f--------------------------\n温泉コマンドの使い方を知るには\nこのチャット文にカーソル合わせてね!\n--------------------------"
  TipMessage: "&a[温泉機能についてのお知らせ]\n&f--------------------------\n&6温かな温泉があなたを待っている\n&f温泉街へは&a/onsen spawn&fで行くことが可能です\n温泉リクエストに関しては\nLIFEの村人取引所にてリクエストチケットが買えます\n温泉リクエストチケットを手に持って\n&a/onsen request 登録したい温泉名\n&fで記入できます\n--------------------------\n"